---
channel: edge
addons:
  nginxproxymanagerstream:
    repository: shambala001/addon-nginx-proxy-manager-with-stream
    target: proxy-manager
    image: ghcr.io/shambala001/nginxproxymanagerstream/{arch}
